### ISSUE TITLE
Vulnerabilidade de Segurança

### ISSUE THREAD

**Issue by Judahh** [FabricaDeSoftwareUniFanor/Apolo#2]
Vulnerabilidade de segurança de nível médio no pacote Microsoft.AspNetCore.All >= 2.0.0
Sugestão: atualizar para Microsoft.AspNetCore.All ~> 2.0.9.

**Comment by igorlucas** [comment]
Como foi feito essa análise? estou curioso em saber rsr. vou verificar a atualização no meu projeto.

**Comment by Judahh** [comment]
Vulnerabilidade conhecida pela plataforma do github, ele mesmo já avisa.

**Comment by igorlucas** [comment]
Foi feita a atualização do pacote em questão no commit **f4d1dd612f23df5fa1cc79433ae1e1994bd1c55b**.
Tudo certo! : )
